name: todolist_get
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  timezone: ^0.9.4

flutter_native_splash:
  color: "#121212"
  image: assets/images/logo_bootsplash.png
  color_dark: "#121212"
  image_dark: assets/images/logo_bootsplash.png

  android_12:
    image: assets/images/logo_bootsplash.png
    icon_background_color: "#121212"
    image_dark: assets/images/logo_bootsplash.png
    icon_background_color_dark: "#121212"

  android: true
  ios: true
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
